version: "3"
services:
        elk:
                image: morgandoc07/elk_support_xivo
                volumes:
                        - ./elkforxivo:/var/tmp/elkforxivo:ro
                ports:
                        - 127.0.0.1:5601:5601
                        - 127.0.0.1:5044:5044
                        - 127.0.0.1:9200:9200
        reverse-proxy:
                image: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/conf.d/default.conf
                        - ./ssl:/root/acme
                ports:
                        - 80:80
                        - 443:443
