version: "3"
services:
        elk:
                image: morgandoc07/elk_support_xivo:latest
                container_name: elk_support-container
                volumes:
                        - ./elkforxivo:/var/tmp/elkforxivo:ro
                        - ./proxy:/opt/kibana/config
                        - ./dashboardJson:/dashboardJson
                ports:
                        - 127.0.0.1:5601:5601
                        - 127.0.0.1:5044:5044
                        - 127.0.0.1:9200:9200

        reverse-proxy:
                image: trafex/php-nginx
                container_name: reverse_proxy-container
                volumes:
                        - ./nginx.conf:/etc/nginx/conf.d/default.conf
                        - ./nginx.conf:/etc/nginx/http.d/default.conf
                        - ./docker-project/php/php.ini:/etc/php8/php.ini
                        - ./ssl:/root
                        - ./docker-project/www/html:/var/lib/nginx/html/ #/var/www/html
                        - ./elkforxivo:/var/lib/nginx/html/elkforxivo #/var/www/html/elkforxivo
                ports:
                        - 80:80
                        - 443:443
                        
#        nginx:
#                build: ./docker-project/nginx/
#                container_name: nginx-container
#                ports:
#                        - 8080:80
#                links:
#                        - php
#                volumes:
#                        - ./docker-project/www/html/:/var/www/html/
#         php:
#                 image: php:7.3-fpm
#                 container_name: php-container
#                 expose:
#                         - 9000
#                 volumes:
#                         - ./docker-project/www/html/:/var/www/html/
#                         - ./docker-project/php:/usr/local/etc/php
#                         - ./elkforxivo:/var/www/html/elkforxivo
