version: "3"
services:
        elk:
                image: morgandoc07/elk_support_xivo:v1.2
                volumes:
                        - /var/tmp/elkforxivo:/var/tmp/elkforxivo:ro
                ports:
                        - 5601:5601
                        - 5044:5044
                        - 9200:9200
